{% set name = "bowtie" %}
{% set version = "0.8.0" %}
{% set sha256 = "b83576e5bac3a9f4c62e0eb38ff898acb0bb7f0fa3807fad110358e3f06d6435" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click
    - eventlet
    - flask
    - flask-socketio
    - future
    - jinja2
    - markdown
    - msgpack-python
    - yarn

test:
  imports:
    - bowtie

about:
  home: https://github.com/jwkvam/bowtie
  license: MIT
  license_file: LICENSE
  summary: 'Interactive Dashboard Toolkit'
  description: |
    Bowtie is a library for writing dashboards in Python. No need to know
    web frameworks or JavaScript, focus on building functionality in Python.
    Interactively explore your data in new ways! Deploy and share with others!
  doc_url: https://bowtie-py.readthedocs.io/
  dev_url: https://github.com/jwkvam/bowtie

extra:
  recipe-maintainers:
    - jwkvam
