travis:
  secure:
    BINSTAR_TOKEN: F1LAoUNaXiDUQC+Xkc5pWSafgsBapsEvEemauBXu2xIZ25TuH5ONPol/UsImF1HSoY43YvI9v6wmsF1/IMXCIXMeDgiZojUSvXAk1qYvTqVpeaMRymgcBLBL8Ayvz3hOkfEOdf4E3LM/E9P4bcHftiJKjbRxUG0HUfEj6tnWFuWlDsCxMyiajbuR6ZXxpC+NahOZmQHMnAwQ7FDad4R7QxbkeiarmW9gm9Et5kNLJRRcaGpdWJaGVdfRmJyk4fZ6emPOdXHfc2q+mEetl/5ws+CORexozhyLu+c7U4dXNA09k2dzPXhSO2oR4g+wZYzJ5KCtA3Y4xLdB/Ti/InIdyosNP4XNLV42VLqSqm3FFrh1h3JgdUytlX6eulZ7RVWQp0uW+lycsDQ+UtCCi+QmsOOQ/GhOLUqk67B1WQf24bQTlx16wQ6H84PZaWFAzkidcczKfnMzWA7fONE813D4qm7vgUOTk5v04HLdfbSHyFzoyOwiQHBZmvG1ylXE/vHVNM8Xlzqz45q+1SmZmGapW/7tTAcjNQYa4wt36f9WmyocLjhjzhD5847yMYOJB/k/gO3+cobl1DZrHQ6Fxf+a8S4zCwKw+K7Yyr7wbpSGzVb6JSDeaSWFxUH16lXhsGjBr/+1sJ76TcsDGILRephg1XfEdWsmnuOHa/QkGeb8W84=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
