travis:
  secure:
    BINSTAR_TOKEN: fIspsOi67AbXPw62Kk24Lp50twsyXUNvoXvQHxmLYjBE0RqXgDu9HVUh5yIoN8I3Pg+H0Kf84yw/GJtc1tYczL9H5yYs0GGs2KuMbNEJZGp+E+th6Ie7kKm6ql90bnp/zszArcBk3fp8gt/6iKcHzTuYVCCkxhNHJWLg5d3OVeIYuY3xyc0nn7DChFiB4B4Kw8yIHiGCnOqhtxDWAh7dFu3c/g1khJcDGhZg8XJLJBtjp43lXcWZF65N6Wa2n6eRyJEuqsqdg0x6zsgU2Nk4XouufosY5MC2p907vxI60hwxUTUBRJKxplLfo62XyrnYorvPCCoX858lW9FTLDJfv4mmg6LIvBOEVlmxrUz3kUHVbZKoa5c2Q18TQU1soepRMuq1iFsWIFq0eUFdhYjNhczDUJVMon78nCGfWPz0NmJ6Y7LUvNq1FPkDVlCBGmMxkfxFt+bK+ObJvTPssxOR9NOlzUElHYJlTmzN1KL4KCacN4j/1O6+o/XMT4wK4Jr6hT1iLytjn/fz7gBLWJztfwrix4OtECoCisAsQXIhtAjg33iWEva/IqjcI/Xg5DiyofC2wOzXJ7mPeLDUVVrGi0EGo4FwKKN6uyfNIBhnc9U0B4ugsBlmtvNNe1E2E7JqAMgoNmb9Xx8/CqjRWNmljOvCyk1v56YCy/xbJGOqCD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
