travis:
  secure:
    BINSTAR_TOKEN: CjE8jnbjOe1Ab+BwEmaie1wPEZtzmi+xyyFNuPgYQ6cW3nxXuBA/9II23zTjj/U8DwKzavkzO20OZhzeXFEfxrixuqIRkW/mpTDqOIrHI/Xpds1IvF3S26z/6Oi6xMb7mFkgGvzk24Z18S6ealeLT1ihUT6lH5jthKWwn+vnG7vasSl4XvJoukKbRUDTDVGtzOoBiR7o3CL17M1Ylt9x4fXXbskCTbwWlX5TH7xqGcy0fqMW7d4pjbDiABAFgEoOSpGhi8pffUrLVLOp/ptgYLInTwREEr+6JXZN/hgYXQ9dW5gVoZRZsXi/79kkY4gduOMvgdRHLW4J/a6+ePfqMxVpROTs2Xv30BSKWTsn+ZZRvotyCLxC7TBQGnQQ8RHG4aB6fPmOaFUiRG3MV9W5qdkuqNILRiE6455UC1mTNarT5PqaJZz4CIr890H5KcpAD1KA4vfCzWzbnT8RSxhJOhqvRubpnBucbboRAuPLawtlsIOfpMgx+GoRN2Iyk/mhV3n/H7uYfTSqvRVSjSixfZ6gWwjWlls2r3BRjbUvcN1aRJnLeYHxHzsf6BUjzbMa9DQaGzF/MzC1UmcWubBT85mPl5L5xXcHRU37/Q8rK+yVKLHZDH5XYWRfLFiJM2R2i8bmxexqpmBv5P7AxVUsHqojdFbo6XcbOgd5ZRRT5l0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
