travis:
  secure:
    BINSTAR_TOKEN: iFBRR0bk7BrZCrClFFHTq1QGgD9js58tASy+zHd1jenZquwfI6ZmTLjU44SEjnn+qBX2QZhMVUKzxIUOa1uiMk+iyyzhxtFyIaQrgeblRZPrJbSbbGurGEnx3+8MgR9gH81sOCOixWqR0Wt+4kkDit9Ad9T+iwB8PvGcsWzICG8Lee0gCNt3U6pDUgOwMiATgj+1FiiuLBXYskI2AI3nzoSBmgJalgPrLnvUzRvU1/a7wAqW8Dgf8p917M8sCo6jHXMrb/xIUMUr1iiFjPBO5hwddz7ROM0jy/aI4NGkZt7sykN+6qSJ4PkSjXTFgSkjluxoMKnuuCVFqU5NIgJd6iHwK8SozzeviP9WA56Ej/ja2Ry0Y5cAoXABwgKMK3JJV9JCgg32RWb66jXdABW8WdfNVGzhkY6SzTQEC7LDAyRej3g4t24K4+LRyhRWYn4LRh/yPFybtR0XcUL9F5JntIr6ISm/44Oqg0cXjyXaauv3lf2nn90hS09u9IOkkzop7P1oX/vNEESBYchzmBajz5D93osoP0EJUlCTQvPLlDc+chg/vYwrQpLMnkmpfyAgZn2ZapqearhJmg5uHJE/Xde5B1NoSc6Z9DvlZ50TPr2VOJUt1Cn1M0zB1EoaEEZ7I8j1NRaXue9tK65Kfx4GfMVA2ZXHXDcmsLS4yF3+/rQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
